"""empty message

Revision ID: 4f6c3b920cba
Revises: 7632c2a5255f
Create Date: 2016-02-01 01:30:18.381681

"""

# revision identifiers, used by Alembic.
revision = '4f6c3b920cba'
down_revision = '7632c2a5255f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
