"""empty message

Revision ID: 7632c2a5255f
Revises: 1b966e7f4b9e
Create Date: 2016-02-01 01:00:43.390658

"""

# revision identifiers, used by Alembic.
revision = '7632c2a5255f'
down_revision = '1b966e7f4b9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
